preprocess:
  input_path: data/raw/train.csv
  output_path: data/processed/train_parquet


train:
  random_seed: 42
  rf:
    numTrees: [20, 50, 100]
    maxDepth: [5, 10, 15]
    featureSubsetStrategy: ["sqrt", "log2"]
  crossval:
    folds: 3
    parallelism: 2

drift:
  features: ["Age", "Fare", "Pclass", "SexIndex", "Parch", "Embarked"]
  psi_threshold: 0.1


mlflow:
  experiment_name: RandomForest_Titanic_AutoML
  tracking_uri: http://localhost:5000
  model_name: Titanic_RandomForest

spark:
  executor_cores: 8
  executor_memory: "16g"
  executor_instances: 4